export { default as BugIcon } from './icons/bug.svg';
export { default as CaretIcon } from './icons/caret.svg';
export { default as DocumentIcon } from './icons/document.svg';
export { default as LogoIcon } from './icons/headerLogo.svg';
export { default as RemoveIcon } from './icons/remove.svg';
export { default as CheckIcon } from './icons/switchCheck.svg';
export { default as CrossIcon } from './icons/switchCross.svg';
export { default as ChatIcon } from './icons/floatChat.svg';
export { default as TopIcon } from './icons/floatVector.svg';
export { default as PaginationArrowIcon } from "./icons/paginationArrow.svg"
export { default as DBCardArrowIcon } from "./icons/dbCardArrow.svg"
export { default as DetectFileCardButtonIcon } from "./icons/detectFileCardButton.svg"
export { default as ExternalLinkIcon } from "./icons/externalLinkIcon.svg"
export { default as PinIcon } from "./icons/pinIcon.svg"
export { default as BigPinIcon } from "./icons/bigPinIcon.svg"
export { default as ShareIcon } from "./icons/sharingIcon.svg"
export { default as SpacSpaceLogoIcon } from "./icons/spacSpaceLogo.svg"
